const root=document.documentElement,header=document.querySelector('[data-header]'),menuButton=document.querySelector('[data-menu-button]'),menu=document.querySelector('[data-menu]'),themeButton=document.querySelector('[data-theme-button]'),toast=document.querySelector('[data-toast]');
const saved=localStorage.getItem('blog-theme'),prefersDark=matchMedia('(prefers-color-scheme:dark)').matches;if(saved==='dark'||(!saved&&prefersDark))root.dataset.theme='dark';
function themeLabel(){if(!themeButton)return;const dark=root.dataset.theme==='dark';themeButton.setAttribute('aria-label',dark?'라이트 모드로 전환':'다크 모드로 전환');const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=dark?'#151613':'#f7f7f2'}themeLabel();
themeButton?.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('blog-theme',root.dataset.theme);themeLabel()});
function closeMenu(){menu?.classList.remove('open');menuButton?.setAttribute('aria-expanded','false')}menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menu?.classList.toggle('open',!open);menuButton.setAttribute('aria-expanded',String(!open))});menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>8),{passive:true});document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
const observer=new IntersectionObserver((entries,o)=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
function showToast(message){if(!toast)return;toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
document.querySelectorAll('[data-demo-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;showToast(form.dataset.success||'완료되었습니다.');form.reset()}));
const search=document.querySelector('[data-post-search]'),filters=document.querySelectorAll('[data-filter]'),posts=document.querySelectorAll('[data-post]'),empty=document.querySelector('[data-empty-state]');let category='전체';function filterPosts(){const q=search?.value.trim().toLowerCase()||'';let count=0;posts.forEach(post=>{const visible=(category==='전체'||post.dataset.category===category)&&post.textContent.toLowerCase().includes(q);post.hidden=!visible;if(visible)count++});empty?.classList.toggle('show',count===0)}filters.forEach(button=>button.addEventListener('click',()=>{category=button.dataset.filter;filters.forEach(x=>x.classList.toggle('active',x===button));filterPosts()}));search?.addEventListener('input',filterPosts);
const draftForm=document.querySelector('[data-draft-form]'),draftButton=document.querySelector('[data-save-draft]');draftButton?.addEventListener('click',()=>{localStorage.setItem('blog-draft',JSON.stringify(Object.fromEntries(new FormData(draftForm).entries())));showToast('임시 저장했습니다.')});if(draftForm){const draft=JSON.parse(localStorage.getItem('blog-draft')||'null');if(draft)Object.entries(draft).forEach(([key,value])=>{if(draftForm.elements[key])draftForm.elements[key].value=value});draftForm.addEventListener('submit',e=>{e.preventDefault();if(!draftForm.reportValidity())return;localStorage.removeItem('blog-draft');showToast('글을 발행했습니다.');setTimeout(()=>location.href='posts.html',900)})}

const authTokenKey='minjun-blog-session',authUserKey='minjun-blog-user';
function storedUser(){try{return JSON.parse(localStorage.getItem(authUserKey)||'null')}catch(_){localStorage.removeItem(authUserKey);return null}}
function prepareAuthNavigation(){document.querySelectorAll('.menu').forEach(menu=>{if(menu.querySelector('[data-auth-guest]'))return;const signup=menu.querySelector('a[href="signup.html"]');if(!signup)return;let login=menu.querySelector('a[href="login.html"]');if(!login){login=document.createElement('a');login.href='login.html';login.textContent='로그인';signup.before(login)}login.dataset.authGuest='';signup.dataset.authGuest='';const profile=document.createElement('a');profile.href='profile.html';profile.textContent='프로필';profile.dataset.authUser='';profile.hidden=true;const logout=document.createElement('a');logout.href='#logout';logout.textContent='로그아웃';logout.className='join-link';logout.dataset.authUser='';logout.dataset.logout='';logout.hidden=true;signup.after(profile,logout)})}
function renderAuthNavigation(user){document.querySelectorAll('[data-auth-guest]').forEach(el=>el.hidden=Boolean(user));document.querySelectorAll('[data-auth-user]').forEach(el=>el.hidden=!user)}
async function loadAuthConfig(){if(window.APP_CONFIG)return;await new Promise(resolve=>{const script=document.createElement('script');script.src='js/config.js';script.onload=resolve;script.onerror=resolve;document.head.append(script)})}
async function handleLogout(event){event.preventDefault();const token=localStorage.getItem(authTokenKey);try{await loadAuthConfig();const apiUrl=window.APP_CONFIG?.appsScriptUrl;if(token&&apiUrl){await fetch(apiUrl,{method:'POST',redirect:'follow',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'logout',token})})}}catch(_){}finally{localStorage.removeItem(authTokenKey);localStorage.removeItem(authUserKey);location.href='index.html'}}
prepareAuthNavigation();renderAuthNavigation(storedUser());document.querySelectorAll('[data-logout]').forEach(el=>el.addEventListener('click',handleLogout));
