const root=document.documentElement,header=document.querySelector('[data-header]'),menuButton=document.querySelector('[data-menu-button]'),menu=document.querySelector('[data-menu]'),themeButton=document.querySelector('[data-theme-button]'),toast=document.querySelector('[data-toast]');
const saved=localStorage.getItem('blog-theme'),prefersDark=matchMedia('(prefers-color-scheme:dark)').matches;if(saved==='dark'||(!saved&&prefersDark))root.dataset.theme='dark';
function themeLabel(){if(!themeButton)return;const dark=root.dataset.theme==='dark';themeButton.setAttribute('aria-label',dark?'라이트 모드로 전환':'다크 모드로 전환');const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=dark?'#151613':'#f7f7f2'}themeLabel();
themeButton?.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('blog-theme',root.dataset.theme);themeLabel()});
function closeMenu(){menu?.classList.remove('open');menuButton?.setAttribute('aria-expanded','false')}menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menu?.classList.toggle('open',!open);menuButton.setAttribute('aria-expanded',String(!open))});menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>8),{passive:true});document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
const observer=new IntersectionObserver((entries,o)=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
function showToast(message){if(!toast)return;toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
document.querySelectorAll('[data-demo-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;showToast(form.dataset.success||'완료되었습니다.');form.reset()}));
const search=document.querySelector('[data-post-search]'),filters=document.querySelectorAll('[data-filter]'),posts=document.querySelectorAll('[data-post]'),empty=document.querySelector('[data-empty-state]');let category='전체';function filterPosts(){const q=search?.value.trim().toLowerCase()||'';let count=0;posts.forEach(post=>{const visible=(category==='전체'||post.dataset.category===category)&&post.textContent.toLowerCase().includes(q);post.hidden=!visible;if(visible)count++});empty?.classList.toggle('show',count===0)}filters.forEach(button=>button.addEventListener('click',()=>{category=button.dataset.filter;filters.forEach(x=>x.classList.toggle('active',x===button));filterPosts()}));search?.addEventListener('input',filterPosts);
const draftForm=document.querySelector('[data-draft-form]'),draftButton=document.querySelector('[data-save-draft]');draftButton?.addEventListener('click',()=>{localStorage.setItem('blog-draft',JSON.stringify(Object.fromEntries(new FormData(draftForm).entries())));showToast('임시 저장했습니다.')});if(draftForm){const draft=JSON.parse(localStorage.getItem('blog-draft')||'null');if(draft)Object.entries(draft).forEach(([key,value])=>{if(draftForm.elements[key])draftForm.elements[key].value=value});draftForm.addEventListener('submit',e=>{e.preventDefault();if(!draftForm.reportValidity())return;localStorage.removeItem('blog-draft');showToast('글을 발행했습니다.');setTimeout(()=>location.href='posts.html',900)})}
